session: { { session } }

root: { { root } }

# command to run before session starts
# before_start:
#   -

# command to run after session stops
# stop:
#   -

windows:
  - name: { { session } }

  - name: scratch
# -- schema ---

# window
#   name:
#   root:
#   manual:
#   commands:
#   layout:
#   panes:
#
# pane
#   type:
#   root:
#   layout:
#   commands:
