name: Publish

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish
         run: |
           ./bin/build.sh
           ./bin/publish.sh

