name: Publish

on:
    workflow_run:
        workflows: ["Release"]
        types: [completed]

jobs:
    release:
        name: Publish Release
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: build
              run: |
                  bin/build.sh

            - name: release
              run: |
                  bin/publish.sh
